jobs:
  - script: >
      job('hadoop') {
        parameters {
                  stringParam('REPO', 'https://github.com/apache/hadoop.git', 'Hadoop repo to pull upstream code')
                  stringParam('BRANCH', 'trunk', 'Git branch')
                  stringParam('MVN_PARAMS', 'clean package -fae -Pnative -Pdist -Dmaven.javadoc.skip=true -DskipTests', 'Maven parameters')        
              }
          properties {
              rebuild {
              autoRebuild(false)
          }
          }            
          scm {
          git {
              remote {
                  url('$REPO')
              }
              branch('*/$BRANCH')

          }
          }
        triggers {
          cron('@monthly')
        }
        concurrentBuild(false)
      
        steps {
          shell('bash /hadoop_jenkins.sh')
        }
      
        publishers {
          archiveJunit('**/target/surefire-reports/*.xml') {
              allowEmptyResults()
              retainLongStdout(false)
              healthScaleFactor(1.0)
          }
        }
      }

      job('hadoop-sls-build') {
        parameters {
              stringParam('REPO', 'https://github.com/apache/hadoop.git', 'Hadoop repo to pull upstream code')
              stringParam('BASELINE_BRANCH', 'trunk', 'Git branch')
              stringParam('BRANCH', 'trunk', 'Git branch')
              stringParam('MVN_PARAMS', 'clean package -fae -Pnative -Pdist -Dmaven.javadoc.skip=true -DskipTests', 'Maven parameters')        
            }
        properties {
            
            rebuild {
            autoRebuild(false)
        }
        }
        scm {
        git {
            remote {
                url('$REPO')
            }
            branch('*/BASELINE_BRANCH')
            branch('*/$BRANCH')

        }
        }
      triggers {
        cron('@monthly')
        }
      concurrentBuild(false)
     
      steps {
        shell('bash /sls_jenkins.sh')
      }
    
      publishers {
        archiveJunit('**/target/surefire-reports/*.xml') {
            allowEmptyResults()
            retainLongStdout(false)
            healthScaleFactor(1.0)
        }
        }
      }

      job('sls-runner') {
        parameters {
              stringParam('REPO', 'https://github.com/apache/hadoop.git', 'CDH repo')
              stringParam('BRANCH', 'sls-tests', 'Git branch')
              choiceParam('SCHEDULER_TYPE', ['fair (default)', 'capacity'], 'Type of the scheduler, should be either "fair" or "capacity"')
              stringParam('SLS_BUILD_NUMBER', '', 'The build number of the SLS build job. If empty, the latest build will be used') 
              stringParam('NUMBER_OF_RUNS', '1', 'Number of times SLS testing will be performed')
              stringParam('WORKLOAD_TYPES', 'resource-types, capacity', 'Comma seperated list of workloads. A workload defines how the SLS input data is generated.')              
            }
        properties {
            
            rebuild {
            autoRebuild(false)
        }
        }
        scm {
        git {
            remote {
                url('$REPO')
            }
            branch('*/$BRANCH')

        }
        }
      triggers {
        cron('@monthly')
        }
      concurrentBuild(false)
     
      steps {
        shell('bash /sls_runner_jenkins.sh')
      }
    
      publishers {
        archiveJunit('**/target/surefire-reports/*.xml') {
            allowEmptyResults()
            retainLongStdout(false)
            healthScaleFactor(1.0)
        }
        }
      }